name: TagBit
title: TagBit | A place to find answers.
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
paginate: 11
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - url: /tags
    title: Tags
  - title: Feed
    url: /feed.xml
email: youremail@xyz.com
disqus_username: disqus_username
