name: tagbit
title: tagbit | A creative company.
description: A design and development based community platform, focusing to
  deliver the contents absolutely for noobs and it begins from scratch to pro.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
paginate: 11
menu:
  - title: Home
    url: /
  - title: About
    url: tagbit.tk/about
  - title: Contact
    url: https://tagbit.tk/contact
  - url: https://tagbit.tk/tags
    title: Tags
  - title: Feed
    url: https://tagbit.tk/feed.xml
email: tagbit.community@gmail.com
disqus_username: tagbit
