name: tagbit
title: tagbit | A creative company.
description: A design and development based community platform, focusing to
  deliver the contents absolutely for noobs and it begins from scratch to pro.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
paginate: 11
menu:
  - title: Home
    url: /
  - url: /tags
    title: Tags
  - title: Authors
    url: /authors/
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: tagbit.community@gmail.com
disqus_username: tagbit
